### ISSUE TITLE
App force close on 7.1.2 Dirty Unicorns. Honor 5x 

### ISSUE THREAD

**Issue by methuselahin** [75py/CallConfirm#5]
@75py  the bug can easily created. All permission were given to the app. First time app worked perfectly fine. But on the second time as video shows have error. The phone was dual sim and the option to ask for which sim is required to call was selected. logcat is attached. 
beginning of crash
[ 07-17 14:51:33.578  5911: 5911 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.nagopy.android.callconfirm, PID: 5911
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nagopy.android.callconfirm/com.nagopy.android.callconfirm.view.ConfirmActivity}: java.lang.RuntimeException: phoneNumber contains illegal chars
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6208)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.RuntimeException: phoneNumber contains illegal chars
	at com.nagopy.android.callconfirm.d.a.a(Unknown Source)
	at com.nagopy.android.callconfirm.view.ConfirmActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	... 9 more

[ 07-17 14:51:34.973   356:  638 E/         ]
tfa98xx_open

[ 07-17 14:51:34.975   356:  638 E/         ]
tfa98xx_open 1 rev = 18, error = 0

[ 07-17 14:51:34.976   356:  638 E/         ]
tfa98xx_open 2 rev = 18, error = 0

[ 07-17 14:51:34.976   356:  638 E/         ]
Tfa98xx_Open err= 0

[ 07-17 14:51:34.979   356:  638 E/         ]
TFA98XX_STATUSREG status = d05f

[ 07-17 14:51:34.986   356:  638 E/         ]
TFA98XX_STATUSREG status = d05f

[ 07-17 14:51:34.992   356:  638 E/         ]
TFA98XX_STATUSREG status = d05f

[ 07-17 14:51:34.998   356:  638 E/         ]
TFA98XX_STATUSREG status = d05f

[ 07-17 14:51:35.006   356:  638 E/         ]
TFA98XX_STATUSREG status = d05f

[ 07-17 14:51:35.012   356:  638 E/         ]
TFA98XX_STATUSREG status = c05f

[ 07-17 14:51:35.013   356:  638 E/         ]
tfa98xx_close

[ 07-17 14:51:35.013   356:  638 E/         ]
tfa98xx_close handle = 0

[ 07-17 14:51:35.013   356:  638 E/tfa98xx  ]
device goes to stop success

[ 07-17 14:51:46.115  6083: 6083 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.nagopy.android.callconfirm, PID: 6083
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nagopy.android.callconfirm/com.nagopy.android.callconfirm.view.ConfirmActivity}: java.lang.RuntimeException: phoneNumber contains illegal chars
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2745)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6208)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.RuntimeException: phoneNumber contains illegal chars
	at com.nagopy.android.callconfirm.d.a.a(Unknown Source)
	at com.nagopy.android.callconfirm.view.ConfirmActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)

[Video error.zip](https://github.com/75py/CallConfirm/files/1152109/Video.error.zip)

**Comment by 75py** [comment]
@sachoosaini Thank you for reporting.
I tried this bugfix but cannot reproduce it.
I don't know how to emulate a dual sim card device...

Anyway, I modified phone numbers validation. #9
Could you retry it in version 0.2.0?

**Comment by sachoosaini** [comment]
Yes I will.... Changed ROM though... Will check
